llm:
  api_type: "openai"  # or azure / ollama / open_llm etc. Check LLMType for more options
  base_url: "YOUR_BASE_URL"
  api_key: "YOUR_API_KEY"
  model: "gpt-4-turbo-preview"  # or gpt-3.5-turbo-1106 / gpt-4-1106-preview
  proxy: "YOUR_PROXY"  # for LLM API requests
  pricing_plan: "" # Optional. If invalid, it will be automatically filled in with the value of the `model`.
  # Azure-exclusive pricing plan mappingsï¼š
  # - gpt-3.5-turbo 4k: "gpt-3.5-turbo-1106"
  # - gpt-4-turbo: "gpt-4-turbo-preview"
  # - gpt-4-turbo-vision: "gpt-4-vision-preview"
  # - gpt-4 8k: "gpt-4"
  # See for more: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/

repair_llm_output: true  # when the output is not a valid json, try to repair it

proxy: "YOUR_PROXY"  # for tools like requests, playwright, selenium, etc.

search:
  api_type: "google"
  api_key: "YOUR_API_KEY"
  cse_id: "YOUR_CSE_ID"

browser:
  engine: "playwright"  # playwright/selenium
  browser_type: "chromium"  # playwright: chromium/firefox/webkit; selenium: chrome/firefox/edge/ie

mermaid:
  engine: "pyppeteer"
  path: "/Applications/Google Chrome.app"

redis:
  host: "YOUR_HOST"
  port: 32582
  password: "YOUR_PASSWORD"
  db: "0"

s3:
  access_key: "YOUR_ACCESS_KEY"
  secret_key: "YOUR_SECRET_KEY"
  endpoint: "YOUR_ENDPOINT"
  secure: false
  bucket: "test"


azure_tts_subscription_key: "YOUR_SUBSCRIPTION_KEY"
azure_tts_region: "eastus"

iflytek_api_id: "YOUR_APP_ID"
iflytek_api_key: "YOUR_API_KEY"
iflytek_api_secret: "YOUR_API_SECRET"

metagpt_tti_url: "YOUR_MODEL_URL"
